image: node:18
pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - .next/**
      - step:
          name: Remove Build Folder
          script:
            - ssh $USER@$SERVER "sudo rm -rf /var/www/html/raizeadminnextjs/.next"
      - step:
          name: Add Build Folder
          script:
            - ssh $USER@$SERVER "sudo mkdir /var/www/html/raizeadminnextjs/.next"
      - step:
          name: Add Folder Permission
          script:
            - ssh $USER@$SERVER "sudo chmod 777 /var/www/html/raizeadminnextjs/.next"
      - step:
          name: Deploy artifacts using SCP to PROD 
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/html/raizeadminnextjs/.next'
                LOCAL_PATH: '.next/*'
      - step:
          name: Pm2 restart
          script:
            - ssh $USER@$SERVER "pm2 restart raizeadminnextjs"
    staging:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - .next/**
            
      - step:
          name: Remove Build Folder
          script:
            - ssh $USERSTAGING@$SERVERSTAGING "sudo rm -rf /var/www/html/raizeadminnextjs/.next"
      - step:
          name: Add Build Folder
          script:
            - ssh $USERSTAGING@$SERVERSTAGING "sudo mkdir /var/www/html/raizeadminnextjs/.next"
      - step:
          name: Add Folder Permission
          script:
            - ssh $USERSTAGING@$SERVERSTAGING "sudo chmod 777 /var/www/html/raizeadminnextjs/.next"            
      - step:
          name: Deploy artifacts using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $USERSTAGING
                SERVER: $SERVERSTAGING
                REMOTE_PATH: '/var/www/html/raizeadminnextjs/.next'
                LOCAL_PATH: '.next/*'
      - step:
          name: PM2 restart
          script:
            - ssh $USERSTAGING@$SERVERSTAGING "pm2 restart raizeadminnextjs"